# Utilización de la librería Pandas

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data/base_datos_2008.csv", nrows = 100000)

Year - year of the flight (stored as factor).
Month - month of the flight (stored as factor).
DayOfMonth - day of the month (1 to 31) (stored as integer).
DayOfWeek - day of the week (stored as factor).
DepTime - actual departure time (stored as float).
CRSDepTime - scheduled departure time (stored as float).
ArrTime - actual arrival time (stored as float).
CRSArrTime - scheduled arrival time (stored as float).
UniqueCarrier - carrier ID (stored as factor).
FlightNum - flight number (stored as factor).
TailNum - plane's tail number (stored as factor).
ActualElapsedTime - actual elapsed time of the flight, in minutes (stored as integer).
CRSElapsedTime - scheduled elapsed time of the flight, in minutes (stored as integer).
AirTime - airborne time for the flight, in minutes (stored as integer).
ArrDelay - arrival delay, in minutes (stored as integer).
DepDelay - departure delay, in minutes (stored as integer).
Origin - originating airport (stored as factor).
Dest - destination airport (stored as factor).
Distance - flight distance (stored as integer).
TaxiIn - taxi time from wheels down to arrival at the gate, in minutes (stored as integer).
TaxiOut - taxi time from departure from the gate to wheels up, in minutes (stored as integer).
Cancelled - cancellation status (stored as logical).
CancellationCode - cancellation code, if applicable (stored as factor).
Diverted - diversion status (stored as logical).
CarrierDelay - delay, in minutes, attributable to the carrier (stored integer).
WeatherDelay - delay, in minutes, attributable to weather factors (stored as integer).
NASDelay - delay, in minutes, attributable to the National Aviation System (stored as integer).
SecurityDelay - delay, in minutes, attributable to security factors (stored as integer).
LateAircraftDelay - delay, in minutes, attributable to late-arriving aircraft (stored as integer).

In [4]:
# Con head() se muestran las 5 primeras filas de nuestros dataframe.
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [5]:
# Si queremos ver más filas, podemos hacer 
df.head(10)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,4.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
7,2008,1,3,4,1039.0,1040,1132.0,1150,WN,535,...,7.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
8,2008,1,3,4,617.0,615,652.0,650,WN,11,...,6.0,19.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
9,2008,1,3,4,1620.0,1620,1639.0,1655,WN,810,...,3.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [6]:
df.tail()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
99995,2008,1,25,5,2204.0,1935,106.0,2257,XE,7676,...,4.0,17.0,0,NaN,0,0.0,0.0,0.0,0.0,129.0
99996,2008,1,26,6,1933.0,1935,2234.0,2257,XE,7676,...,4.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
99997,2008,1,27,7,2047.0,1935,2400.0,2257,XE,7676,...,6.0,18.0,0,NaN,0,23.0,0.0,0.0,0.0,40.0
99998,2008,1,28,1,1956.0,1935,2308.0,2257,XE,7676,...,5.0,25.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
99999,2008,1,29,2,1938.0,1935,2308.0,2257,XE,7676,...,5.0,41.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [9]:
# frac = 1 nos permite reordenar aleatoriamente el 100% de lo que tenemos en el dataframe
df = df.sample(frac = 1)
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
7730,2008,1,5,6,1941.0,1840,2102.0,2005,WN,2807,...,5.0,6.0,0,NaN,0,4.0,0.0,0.0,0.0,53.0
99892,2008,1,11,5,843.0,845,930.0,935,XE,7673,...,5.0,23.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
38515,2008,1,15,2,1847.0,1830,2141.0,2135,WN,2437,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
12046,2008,1,7,1,1859.0,1905,2100.0,2115,WN,1668,...,5.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
15757,2008,1,8,2,1614.0,1610,1722.0,1725,WN,2801,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [12]:
df.tail()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
34191,2008,1,13,7,1714.0,1710,1859.0,1925,WN,442,...,5.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3494,2008,1,4,5,621.0,620,647.0,655,WN,1580,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
31280,2008,1,12,6,NaN,1900,NaN,2010,WN,2273,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
54915,2008,1,20,7,1438.0,1440,1723.0,1720,WN,1770,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
51,2008,1,3,4,1150.0,1145,1303.0,1305,WN,2124,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [10]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [11]:
# Escogemos la columna DepTime
df.DepTime

7730     1941.0
99892     843.0
38515    1847.0
12046    1859.0
15757    1614.0
          ...
34191    1714.0
3494      621.0
31280       NaN
54915    1438.0
51       1150.0
Name: DepTime, Length: 100000, dtype: float64

In [13]:
# Con esta instrucción nos muestra los tipos de variables que tenemos en el dataframe.
df.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime         int64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [14]:
# Otra forma de ver los datos en formato array
df.values

array([[2008, 1, 5, ..., 0.0, 0.0, 53.0],
       [2008, 1, 11, ..., nan, nan, nan],
       [2008, 1, 15, ..., nan, nan, nan],
       ...,
       [2008, 1, 12, ..., nan, nan, nan],
       [2008, 1, 20, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan]], dtype=object)

In [15]:
# Podemos definir un segundo dataframe con las primeras 10 filas y lo guardamos en memoria. Nos puede ayudar
# a hacer un procesamiento de parte de los datos.
df2 = df.head(10)

In [16]:
# Nos va a mostrar solo 10 filas... 
df2.head(20)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
7730,2008,1,5,6,1941.0,1840,2102.0,2005,WN,2807,...,5.0,6.0,0,NaN,0,4.0,0.0,0.0,0.0,53.0
99892,2008,1,11,5,843.0,845,930.0,935,XE,7673,...,5.0,23.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
38515,2008,1,15,2,1847.0,1830,2141.0,2135,WN,2437,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
12046,2008,1,7,1,1859.0,1905,2100.0,2115,WN,1668,...,5.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
15757,2008,1,8,2,1614.0,1610,1722.0,1725,WN,2801,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
50807,2008,1,18,5,1106.0,1105,1201.0,1205,WN,1153,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
47282,2008,1,17,4,925.0,930,1111.0,1110,WN,1479,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
75673,2008,1,26,6,1537.0,1535,2233.0,2255,WN,3672,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
225,2008,1,3,4,1521.0,1450,1725.0,1655,WN,2726,...,5.0,13.0,0,NaN,0,16.0,0.0,0.0,0.0,14.0
65290,2008,1,23,3,845.0,840,928.0,930,WN,2447,...,4.0,5.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

# Filtrado

In [17]:
# Obtención de información relevante de nuestras filas y columnas de BD
df = pd.read_csv("data/base_datos_2008.csv")

In [18]:
# Filtrado entendemos la información relevante de nuestra BD. 
# Si queremos obtener los 5 primeros valores de la columna ArrDelay
df["ArrDelay"].head()

0   -14.0
1     2.0
2    14.0
3    -6.0
4    34.0
Name: ArrDelay, dtype: float64

In [28]:
# Podemos usar el intervalo de filas que queramos.
df[0:10]

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,4.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
7,2008,1,3,4,1039.0,1040,1132.0,1150,WN,535,...,7.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
8,2008,1,3,4,617.0,615,652.0,650,WN,11,...,6.0,19.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
9,2008,1,3,4,1620.0,1620,1639.0,1655,WN,810,...,3.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [27]:
df[100:1000]

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
100,2008,1,3,4,826.0,825,930.0,925,WN,136,...,2.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
101,2008,1,3,4,2118.0,2015,2224.0,2115,WN,219,...,3.0,17.0,0,NaN,0,17.0,0.0,6.0,0.0,46.0
102,2008,1,3,4,1818.0,1740,1916.0,1840,WN,391,...,2.0,10.0,0,NaN,0,20.0,0.0,0.0,0.0,16.0
103,2008,1,3,4,650.0,650,748.0,750,WN,670,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
104,2008,1,3,4,2146.0,2055,2250.0,2155,WN,815,...,3.0,13.0,0,NaN,0,4.0,0.0,4.0,0.0,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2008,1,3,4,2154.0,2040,2314.0,2205,WN,428,...,4.0,13.0,0,NaN,0,2.0,0.0,0.0,0.0,67.0
996,2008,1,3,4,1322.0,1245,1444.0,1410,WN,500,...,3.0,15.0,0,NaN,0,34.0,0.0,0.0,0.0,0.0
997,2008,1,3,4,701.0,700,823.0,825,WN,565,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
999,2008,1,3,4,834.0,830,955.0,955,WN,762,...,4.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [29]:
# Todos los vuelos que se hayan retrasado > 60 minutos
df[df["ArrDelay"] > 60].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,1333,...,6.0,8.0,0,NaN,0,8.0,0.0,0.0,0.0,72.0
30,2008,1,3,4,2107.0,1945,2334.0,2230,WN,362,...,6.0,7.0,0,NaN,0,5.0,0.0,0.0,0.0,59.0
37,2008,1,3,4,1812.0,1650,1927.0,1815,WN,422,...,6.0,11.0,0,NaN,0,3.0,0.0,0.0,0.0,69.0
49,2008,1,3,4,2245.0,1730,2354.0,1850,WN,186,...,3.0,7.0,0,NaN,0,282.0,0.0,0.0,0.0,22.0
77,2008,1,3,4,958.0,900,1052.0,950,WN,1574,...,4.0,14.0,0,NaN,0,0.0,0.0,4.0,0.0,58.0

In [24]:
# Todos los vuelos que han salido de ATL (Atlanta)
df[df["Origin"] == "ATL"].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
103149,2008,1,21,1,1207.0,1210,1346.0,1335,XE,2349,...,11.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
103572,2008,1,12,6,1458.0,1500,1622.0,1620,XE,2145,...,6.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
104019,2008,1,20,7,1403.0,1330,1625.0,1608,XE,1284,...,6.0,32.0,0,NaN,0,0.0,0.0,17.0,0.0,0.0
104124,2008,1,26,6,1629.0,1630,1832.0,1902,XE,1241,...,9.0,15.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
104485,2008,1,4,5,1336.0,1340,1501.0,1500,XE,2112,...,12.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [30]:
# Vamos a filtrar de forma combinada, Origen Atlanta y el retraso > 60 minutos.
# & == AND; | == OR
df[(df["Origin"] == "ATL") & (df["ArrDelay"] > 60)].head(100)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
109189,2008,1,31,4,1217.0,1210,1511.0,1335,XE,2023,...,21.0,60.0,0,NaN,0,0.0,0.0,96.0,0.0,0.0
110375,2008,1,19,6,1241.0,1215,1735.0,1437,XE,1284,...,12.0,178.0,0,NaN,0,0.0,0.0,164.0,0.0,14.0
121229,2008,1,3,4,1421.0,1200,1526.0,1325,XE,2132,...,9.0,13.0,0,NaN,0,17.0,0.0,0.0,0.0,104.0
132768,2008,1,6,7,1315.0,1130,1410.0,1240,YV,7267,...,3.0,6.0,0,NaN,0,0.0,0.0,90.0,0.0,0.0
133549,2008,1,7,1,2040.0,1800,2156.0,1932,YV,2626,...,12.0,28.0,0,NaN,0,144.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180960,2008,1,8,2,2129.0,2000,2209.0,2025,OO,3928,...,3.0,37.0,0,NaN,0,104.0,0.0,0.0,0.0,0.0
184140,2008,1,10,4,2328.0,2130,13.0,2241,OO,3895,...,4.0,12.0,0,NaN,0,0.0,0.0,0.0,0.0,92.0
185418,2008,1,11,5,1322.0,1215,1419.0,1303,OO,1982,...,4.0,40.0,0,NaN,0,76.0,0.0,0.0,0.0,0.0
185788,2008,1,11,5,1808.0,1650,1900.0,1752,OO,3914,...,3.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,68.0
193117,2008,1,16,3,2322.0,1711,29.0,1718,OO,1986,...,7.0,79.0,0,NaN,0,431.0,0.0,0.0,0.0,0.0

In [31]:
# Podemos seleccionar todos los vuelos cuyo origen sea Houston y Atlanta.
df[df.Origin.isin(["HOU", "ATL"])].head(100)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
3269,2008,1,4,5,1910.0,1910,2025.0,2025,WN,823,...,6.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3270,2008,1,4,5,1345.0,1345,1453.0,1500,WN,901,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3271,2008,1,4,5,736.0,735,839.0,850,WN,957,...,3.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3272,2008,1,4,5,1603.0,1550,1647.0,1635,WN,231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3273,2008,1,4,5,2105.0,2105,2151.0,2150,WN,570,...,7.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364,2008,1,4,5,1942.0,1945,2150.0,2215,WN,389,...,5.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3365,2008,1,4,5,1447.0,1425,1708.0,1650,WN,519,...,6.0,8.0,0,NaN,0,8.0,0.0,0.0,0.0,10.0
3366,2008,1,4,5,2102.0,2015,2314.0,2245,WN,894,...,10.0,8.0,0,NaN,0,0.0,0.0,0.0,0.0,29.0
3367,2008,1,4,5,630.0,615,852.0,840,WN,969,...,6.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3368,2008,1,4,5,1834.0,1730,2051.0,2000,WN,2174,...,5.0,8.0,0,NaN,0,5.0,0.0,0.0,0.0,46.0

In [32]:
# Todos aquellos casos en los que no tenemos ningún valor en la columna ArrDelay
df[pd.isna(df["ArrDelay"])].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
178,2008,1,3,4,NaN,700,NaN,830,WN,126,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
373,2008,1,3,4,NaN,1100,NaN,1215,WN,1146,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
399,2008,1,3,4,NaN,905,NaN,1025,WN,469,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
401,2008,1,3,4,NaN,1620,NaN,1740,WN,618,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
415,2008,1,3,4,NaN,1930,NaN,2035,WN,2528,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN

In [33]:
# Número de filas en la base de datos que no tienen ningún valor en la columna ArrDelay
len(df[pd.isna(df["ArrDelay"])])

154699

# Transformación

In [45]:
df = pd.read_csv("data/base_datos_2008.csv")

In [34]:
# Una transformación es un cambio de la estructura de nuestra BD, empezamos creando una columna nueva.
# Redondeo de una columna existente, retraso / 60.
df["HoursDelay"] = round(df["ArrDelay"] / 60)

In [35]:
# Para visualizar la transformación... 
df["HoursDelay"].head()

0   -0.0
1    0.0
2    0.0
3   -0.0
4    1.0
Name: HoursDelay, dtype: float64

In [38]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,HoursDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,-0.0
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0.0
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,-0.0
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0,1.0

In [39]:
# Eliminamos la columna que acabamos de crear
del(df["HoursDelay"])

In [40]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [41]:
# Si queremos eliminar varias columnas a la vez, podemos hacerlo de la siguiente forma, axis = 1 indica el eje vertical(columna)
df.drop(["Diverted", "Cancelled", "Year"], axis = 1)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Dest,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,...,TPA,810,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,...,TPA,810,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0,620,804.0,750,WN,448,N428WN,...,BWI,515,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,4,926.0,930,1054.0,1100,WN,1746,N612SW,...,BWI,515,3.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,...,BWI,515,3.0,10.0,NaN,2.0,0.0,0.0,0.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7009723,12,13,6,1002.0,959,1204.0,1150,DL,1636,N646DL,...,IAD,533,6.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN
7009724,12,13,6,834.0,835,1021.0,1023,DL,1637,N908DL,...,SAT,874,5.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN
7009725,12,13,6,655.0,700,856.0,856,DL,1638,N671DN,...,ATL,545,24.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
7009726,12,13,6,1251.0,1240,1446.0,1437,DL,1639,N646DL,...,ATL,533,13.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN
7009727,12,13,6,1110.0,1103,1413.0,1418,DL,1641,N908DL,...,ATL,874,8.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Year sigue apareciendo, esto ocurre porque no hemos igualado a nuestro df
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [46]:
# Si queremos que se borre y se guarde, hay que asignarlo a nuestro dataframe
#df = df.drop(["Diverted", "Cancelled", "Year"], axis = 1)

# también podríamos hacer:
df.drop(["Diverted", "Cancelled", "Year"], axis = 1, inplace = True)

In [47]:
df.head()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Dest,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,...,TPA,810,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,...,TPA,810,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0,620,804.0,750,WN,448,N428WN,...,BWI,515,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,4,926.0,930,1054.0,1100,WN,1746,N612SW,...,BWI,515,3.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,...,BWI,515,3.0,10.0,NaN,2.0,0.0,0.0,0.0,32.0

In [48]:
# Drop también funciona para eliminar filas de nuestra BD
df.drop(0)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Dest,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,...,TPA,810,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0,620,804.0,750,WN,448,N428WN,...,BWI,515,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,4,926.0,930,1054.0,1100,WN,1746,N612SW,...,BWI,515,3.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,...,BWI,515,3.0,10.0,NaN,2.0,0.0,0.0,0.0,32.0
5,1,3,4,1940.0,1915,2121.0,2110,WN,378,N726SW,...,JAX,688,4.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7009723,12,13,6,1002.0,959,1204.0,1150,DL,1636,N646DL,...,IAD,533,6.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN
7009724,12,13,6,834.0,835,1021.0,1023,DL,1637,N908DL,...,SAT,874,5.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN
7009725,12,13,6,655.0,700,856.0,856,DL,1638,N671DN,...,ATL,545,24.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
7009726,12,13,6,1251.0,1240,1446.0,1437,DL,1639,N646DL,...,ATL,533,13.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN
7009727,12,13,6,1110.0,1103,1413.0,1418,DL,1641,N908DL,...,ATL,874,8.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
# Borrado de las primeras 100.000 filas
df.drop(range(0,100000))

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Dest,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
100000,1,30,3,1936.0,1935,2258.0,2257,XE,7676,N11176,...,OKC,866,7.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN
100001,1,3,4,607.0,600,858.0,852,XE,7677,N14177,...,SLC,619,7.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN
100002,1,4,5,552.0,600,849.0,852,XE,7677,N33182,...,SLC,619,6.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN
100003,1,5,6,552.0,600,940.0,852,XE,7677,N17169,...,SLC,619,9.0,15.0,NaN,0.0,0.0,48.0,0.0,0.0
100004,1,7,1,637.0,600,935.0,852,XE,7677,N11181,...,SLC,619,4.0,36.0,NaN,37.0,0.0,6.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7009723,12,13,6,1002.0,959,1204.0,1150,DL,1636,N646DL,...,IAD,533,6.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN
7009724,12,13,6,834.0,835,1021.0,1023,DL,1637,N908DL,...,SAT,874,5.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN
7009725,12,13,6,655.0,700,856.0,856,DL,1638,N671DN,...,ATL,545,24.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
7009726,12,13,6,1251.0,1240,1446.0,1437,DL,1639,N646DL,...,ATL,533,13.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN
7009727,12,13,6,1110.0,1103,1413.0,1418,DL,1641,N908DL,...,ATL,874,8.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
# Creamos dos dataframes con los vuelos cuyo origen es ATL y otro df con los vuelos cuyo origen es HOU
dfATL = df[df.Origin == "ATL"]
dfHOU = df[df.Origin == "HOU"]

In [51]:
# Si queremos añadir ambos dataframes
newdf = dfATL.append(dfHOU)

In [52]:
newdf.Origin

103149     ATL
103572     ATL
104019     ATL
104124     ATL
104485     ATL
          ...
7003419    HOU
7004690    HOU
7005947    HOU
7007233    HOU
7008545    HOU
Name: Origin, Length: 470446, dtype: object

# Agrupaciones

In [53]:
df = pd.read_csv("data/base_datos_2008.csv")

In [54]:
# Group by nos permite hacer operaciones matemáticas sencillas agrupando por categorías.
# En este caso se hace una agrupación por DayOfWeek, y se visualiza el retraso máximo de cada día de la semana.
# Trabajamos con la BD de aerolíneas completa y estudiaremos el retraso de los vuelos al llegar al destino.
# DayOfWeek -> Es una agrupación por el día de la semana, y nos da un valor de los retrasos de los vuelos ArrDelay, 
# proporcionando el valor máximo.
df.groupby(by = "DayOfWeek") ["ArrDelay"].max()

DayOfWeek
1    1583.0
2    1951.0
3    1510.0
4    2453.0
5    1707.0
6    1525.0
7    2461.0
Name: ArrDelay, dtype: float64

In [49]:
# Media de retraso para cada día de la semana.
df.groupby(by = "DayOfWeek") ["ArrDelay"].mean()

DayOfWeek
1     8.210850
2     7.481208
3     6.522017
4     8.411599
5    10.953440
6     5.789666
7     9.495886
Name: ArrDelay, dtype: float64

In [50]:
# Mínimo valor
df.groupby(by = "DayOfWeek") ["ArrDelay"].min()

DayOfWeek
1   -519.0
2    -89.0
3    -87.0
4   -129.0
5    -86.0
6    -91.0
7    -92.0
Name: ArrDelay, dtype: float64

In [52]:
# Número de casos, en fines de semana hay menos vuelos.
df.groupby(by = "DayOfWeek") ["ArrDelay"].count()

DayOfWeek
1    1013410
2    1005992
3    1016995
4    1011970
5    1008872
6     841663
7     956127
Name: ArrDelay, dtype: int64

In [53]:
# Resumen estadístico agrupado por día de la semana
df.groupby(by = "DayOfWeek") ["ArrDelay"].describe()

               count       mean        std    min   25%  50%   75%     max
DayOfWeek
1          1013410.0   8.210850  38.013811 -519.0 -10.0 -2.0  12.0  1583.0
2          1005992.0   7.481208  38.361073  -89.0 -11.0 -3.0  11.0  1951.0
3          1016995.0   6.522017  36.024679  -87.0 -10.0 -3.0  10.0  1510.0
4          1011970.0   8.411599  37.397411 -129.0 -10.0 -1.0  12.0  2453.0
5          1008872.0  10.953440  40.252320  -86.0  -9.0  0.0  15.0  1707.0
6           841663.0   5.789666  37.163120  -91.0 -11.0 -3.0   9.0  1525.0
7           956127.0   9.495886  41.759296  -92.0 -10.0 -2.0  12.0  2461.0

In [55]:
# Podemos ver el resumen comparado de las dos variables ArrDelay DepDelay, en este tipo de comparaciones hay que asegurarse
# que estamos comparando variables del mismo tipo.
df.groupby(by = "DayOfWeek") ["ArrDelay", "DepDelay"].mean()

<ipython-input-55-d84f13daf135>:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(by = "DayOfWeek") ["ArrDelay", "DepDelay"].mean()

            ArrDelay   DepDelay
DayOfWeek
1           8.210850  10.269990
2           7.481208   8.976897
3           6.522017   8.289761
4           8.411599   9.772897
5          10.953440  12.158036
6           5.789666   8.645681
7           9.495886  11.568973

In [56]:
# Se pueden realizar operaciones con los objetos Group By, con esta operación podemos analizar el rango de valores
# para cada día de la semana.
df.groupby(by = "DayOfWeek") ["ArrDelay"].max() - df.groupby(by = "DayOfWeek") ["ArrDelay"].min()

DayOfWeek
1    2102.0
2    2040.0
3    1597.0
4    2582.0
5    1793.0
6    1616.0
7    2553.0
Name: ArrDelay, dtype: float64

In [57]:
# Creamos un nuevo Dataframe de los vuelos cuyo origen es Atlanta y Houston
dfATLHOU = df[df.Origin.isin(["ATL", "HOU"])]

In [58]:
# Podemos comparar por ciudades y días de la semana los retraso en la llegada. Esto permite comparar en cuál de las dos
# ciudades los vuelos salen más retrasados, comparando por día de la semana.
dfATLHOU.groupby(by = ["DayOfWeek", "Origin"])["ArrDelay"].mean()

DayOfWeek  Origin
1          ATL        9.123436
           HOU        6.356856
2          ATL        8.933587
           HOU        9.348112
3          ATL        8.809146
           HOU        9.073109
4          ATL       10.186501
           HOU       12.994016
5          ATL       14.797440
           HOU       11.036545
6          ATL        9.511662
           HOU        4.283933
7          ATL       13.798627
           HOU        7.045287
Name: ArrDelay, dtype: float64

In [59]:
# Aquí podemos ver cómo afecta el retraso por cada día de la semana en ambos aeropuertos.
dfATLHOU.groupby(by = ["Origin", "DayOfWeek"])["ArrDelay"].mean()

Origin  DayOfWeek
ATL     1             9.123436
        2             8.933587
        3             8.809146
        4            10.186501
        5            14.797440
        6             9.511662
        7            13.798627
HOU     1             6.356856
        2             9.348112
        3             9.073109
        4            12.994016
        5            11.036545
        6             4.283933
        7             7.045287
Name: ArrDelay, dtype: float64

In [60]:
# Los objetos que hemos creado por agrupación, pueden guardarse.
mygroupby = dfATLHOU.groupby(by = ["Origin", "DayOfWeek"])["ArrDelay"]

In [61]:
#mygroupby.max()
#mygroupby.min()
#mygroupby.mean()
mygroupby.describe()

                    count       mean        std   min   25%  50%   75%     max
Origin DayOfWeek
ATL    1          60598.0   9.123436  30.958642 -69.0  -8.0  1.0  14.0   407.0
       2          59732.0   8.933587  34.750658 -89.0  -9.0 -1.0  13.0   848.0
       3          60245.0   8.809146  34.343042 -56.0  -9.0  0.0  13.0   876.0
       4          59721.0  10.186501  35.261512 -51.0  -8.0  1.0  15.0   571.0
       5          60007.0  14.797440  38.859778 -51.0  -7.0  3.0  20.0   699.0
       6          49734.0   9.511662  36.020584 -61.0 -10.0 -1.0  15.0   483.0
       7          57664.0  13.798627  42.466233 -86.0  -8.0  1.0  17.0   612.0
HOU    1           8205.0   6.356856  28.887113 -47.0  -7.0 -2.0   9.0   383.0
       2           8368.0   9.348112  35.321852 -44.0  -7.0 -1.0  12.0   546.0
       3           8330.0   9.073109  33.191673 -39.0  -7.0 -1.0  12.0   639.0
       4           8188.0  12.994016  39.360946 -42.0  -6.0  1.0  17.0  1082.0
       5           8209.0  11.036545  32.415069 -48.0  -6.0  1.0  16.0   560.0
       6           5614.0   4.283933  32.518381 -47.0  -9.0 -3.0   6.0   917.0
       7           7331.0   7.045287  30.820505 -55.0  -7.0 -1.0  11.0   685.0

# Tratar datos duplicados y perdidos

In [62]:
import pandas as pd
df = pd.read_csv("data/base_datos_2008.csv", nrows = 1e6)

dfduplicate = df.append(df)

In [63]:
dfduplicate = dfduplicate.sample(frac = 1)
dfclean = dfduplicate.drop_duplicates()

In [64]:
len(dfclean) == len(df)

False

In [65]:
# Tenemos 4 filas menos en relación al dataframe original, pensábamos que el df original no tenía filas repetidas 
# y parece ser que sí.
len(dfclean)

999996

In [66]:
# Aprovechamos y realizaremos un borrado de las filas duplicadas quedándonos con el subset DayofMonth (31 días).
# Mantiene una sola fila por cada DayofMonth distinto, en total 31 filas
dfclean.drop_duplicates(subset = "DayofMonth")

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
722667,2008,2,19,2,1439.0,1445,1557.0,1614,XE,2372,...,6.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
799556,2008,2,22,5,922.0,933,1040.0,1039,OO,6473,...,5.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
490286,2008,1,24,4,729.0,735,1235.0,1305,AA,682,...,7.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
646293,2008,2,15,5,1731.0,1710,1833.0,1810,WN,2817,...,8.0,14.0,0,NaN,0,14.0,0.0,2.0,0.0,7.0
110187,2008,1,29,2,1914.0,1805,2138.0,1950,XE,2794,...,14.0,49.0,0,NaN,0,0.0,0.0,39.0,0.0,69.0
173199,2008,1,3,4,1343.0,1343,1446.0,1440,OO,5503,...,14.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
850249,2008,2,2,6,1406.0,1415,1623.0,1648,US,1068,...,6.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
882628,2008,2,28,4,915.0,919,1153.0,1158,US,190,...,7.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
792635,2008,2,18,1,1442.0,1410,1709.0,1637,OO,5932,...,3.0,21.0,0,NaN,0,0.0,0.0,0.0,0.0,32.0
131803,2008,1,4,5,1338.0,1345,1643.0,1651,YV,7175,...,7.0,19.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
569050,2008,1,31,4,1643.0,1550,27.0,2359,CO,1503,...,7.0,13.0,0,NaN,0,5.0,0.0,0.0,0.0,23.0
378964,2008,1,8,2,1849.0,1845,1922.0,1919,HA,549,...,5.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
751130,2008,2,6,3,2034.0,2036,2306.0,2301,OH,5394,...,5.0,32.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
775299,2008,2,7,4,1312.0,1315,1423.0,1407,OO,5881,...,4.0,32.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
906543,2008,2,27,3,1305.0,1315,1532.0,1551,DL,1582,...,8.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
162516,2008,1,21,1,2015.0,2000,2059.0,2040,OH,5015,...,4.0,23.0,0,NaN,0,15.0,0.0,4.0,0.0,0.0
30360,2008,1,12,6,713.0,650,933.0,925,WN,322,...,2.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
200539,2008,1,20,7,1551.0,1545,1717.0,1710,OO,6491,...,3.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
864215,2008,2,14,4,801.0,805,917.0,931,US,450,...,10.0,23.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
183424,2008,1,9,3,1748.0,1552,1822.0,1633,OO,6338,...,3.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,109.0
967187,2008,2,1,5,1452.0,1455,1636.0,1630,MQ,3210,...,14.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
566311,2008,1,25,5,1546.0,1510,1858.0,1848,CO,1182,...,7.0,22.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
630282,2008,2,10,7,2111.0,2105,2236.0,2235,WN,1274,...,7.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
261893,2008,1,5,6,1703.0,1710,1908.0,1919,US,1730,...,7.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
344725,2008,1,30,3,1225.0,1145,1340.0,1259,EV,4875,...,12.0,9.0,0,NaN,0,40.0,0.0,1.0,0.0,0.0
288747,2008,1,26,6,1751.0,1757,1754.0,1808,US,294,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
901502,2008,2,23,6,953.0,955,1136.0,1152,DL,1593,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
271895,2008,1,13,7,2149.0,2159,613.0,643,US,144,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
574479,2008,1,17,4,753.0,800,1028.0,1032,CO,659,...,6.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
27476,2008,1,11,5,1601.0,1540,1902.0,1850,WN,79,...,6.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
159992,2008,1,16,3,1440.0,1440,1620.0,1629,OH,5517,...,6.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [67]:
# Vamos a ver cómo gestionamos los datos faltantes, queremos 25 columnas sin valores faltantes de las 29 totales
df.dropna(thresh = 25)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,1333,...,6.0,8.0,0,NaN,0,8.0,0.0,0.0,0.0,72.0
16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,675,...,7.0,8.0,0,NaN,0,3.0,0.0,0.0,0.0,12.0
18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,4,...,4.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999973,2008,2,23,6,1306.0,1235,1514.0,1415,MQ,4694,...,3.0,50.0,0,NaN,0,31.0,0.0,28.0,0.0,0.0
999983,2008,2,28,4,1458.0,1235,1645.0,1415,MQ,4694,...,3.0,37.0,0,NaN,0,0.0,0.0,7.0,0.0,143.0
999988,2008,2,4,1,1754.0,1655,2056.0,2005,MQ,4695,...,2.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,51.0
999989,2008,2,5,2,1812.0,1655,2129.0,2005,MQ,4695,...,4.0,12.0,0,NaN,0,10.0,0.0,7.0,0.0,67.0
999994,2008,2,11,1,1717.0,1655,2030.0,2005,MQ,4695,...,4.0,23.0,0,NaN,0,0.0,0.0,3.0,0.0,22.0

In [68]:
# Si el df va creciendo aplicamos una función para que nos quedemos con las filas que tienen al menos n-2 columnas sin datos
df.dropna(thresh=len(df.columns)-2)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,1333,...,6.0,8.0,0,NaN,0,8.0,0.0,0.0,0.0,72.0
16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,675,...,7.0,8.0,0,NaN,0,3.0,0.0,0.0,0.0,12.0
18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,4,...,4.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999973,2008,2,23,6,1306.0,1235,1514.0,1415,MQ,4694,...,3.0,50.0,0,NaN,0,31.0,0.0,28.0,0.0,0.0
999983,2008,2,28,4,1458.0,1235,1645.0,1415,MQ,4694,...,3.0,37.0,0,NaN,0,0.0,0.0,7.0,0.0,143.0
999988,2008,2,4,1,1754.0,1655,2056.0,2005,MQ,4695,...,2.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,51.0
999989,2008,2,5,2,1812.0,1655,2129.0,2005,MQ,4695,...,4.0,12.0,0,NaN,0,10.0,0.0,7.0,0.0,67.0
999994,2008,2,11,1,1717.0,1655,2030.0,2005,MQ,4695,...,4.0,23.0,0,NaN,0,0.0,0.0,3.0,0.0,22.0

In [69]:
# Si nos interesa filtrar por una columna en concreto, podemos usar la misma función con subset a la columna que queremos no 
# tenga datos NaN (vacío)
df.dropna(subset = ["CancellationCode"])

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
178,2008,1,3,4,NaN,700,NaN,830,WN,126,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
373,2008,1,3,4,NaN,1100,NaN,1215,WN,1146,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
399,2008,1,3,4,NaN,905,NaN,1025,WN,469,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
401,2008,1,3,4,NaN,1620,NaN,1740,WN,618,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
415,2008,1,3,4,NaN,1930,NaN,2035,WN,2528,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999913,2008,2,11,1,NaN,855,NaN,1210,MQ,4693,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
999919,2008,2,17,7,NaN,855,NaN,1210,MQ,4693,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
999961,2008,2,17,7,NaN,1445,NaN,1630,MQ,4694,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
999971,2008,2,22,5,NaN,1235,NaN,1415,MQ,4694,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
999999,2008,2,17,7,NaN,1655,NaN,2005,MQ,4695,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN

# Librería Numpy

In [2]:
# Numpy es un paquete orientado al análisis matemático y científico, 
# viene incorporado dentro de Anaconda, no hay que instalarlo.
import numpy as np

In [71]:
# Creamos un numpy array
valoraciones = np.array([[8,7,8,5], [2,6,8,1], [8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

Podemos pensar que cada una de las filas corresponden a tres clientes que han valorado cuatro productos, cada una de las 
columnas

In [72]:
# ¿Cómo podemos acceder a la información? La primera dimensión en el ejemplo [0] son las filas, la segunda las columnas [1]
valoraciones[0][1]

7

In [73]:
# Una alternativa es
valoraciones[0,1]

7

In [74]:
# Si añadimos nuevas dimensiones...
valoraciones2 = np.array([[[8,7,8,5], [2,5,4,2]], [[2,6,8,4], [8,9,7,4]], [[8,8,9,3], [10,9,10,8]]])

In [75]:
# En este caso tenemos de igual forma tres clientes que han podido emitir sus valoraciones en años distintos.
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  4,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [76]:
# Podemos acceder a los elementos de la siguiente forma. ¿A qué elemento nos estamos refiriendo?
valoraciones2[0,0,3]

5

In [77]:
# También podemos inicializar un array de las dimensiones del anterior, por ejemplo:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [78]:
# Podemos hacer operaciones entre arrays de mismo tamaño, con np.ones generamos un objeto con las dimensiones llenas de 1's.
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  5.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [79]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  4,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [80]:
# A los arrays les podemos aplicar muchas funciones, algunos ejemplos:
# En este caso nos devuelve la media de todos los valores del array original (3,2,4)
np.mean(valoraciones2)

6.416666666666667

In [81]:
# Podemos además indicar en qué eje queremos que nos calcule la media, por ejemplo:
np.mean(valoraciones2, axis = 0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.        , 4.66666667]])

El primer elemento devuelto es la media entre 8, 2, 8; 6.66 es la media entre 2, 8 y 10... y así sucesivamente.

In [82]:
# Podemos cambiar el eje...
np.mean(valoraciones2, axis = 1)

array([[5. , 6. , 6. , 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

De esta forma el primer 5 es la media entre 8 y 2; El siguiente 5 entre 2 y 8; y el 9 entre 8 y 10.

In [96]:
# Si lo hacemos con el último eje, obtenemos:
np.mean(valoraciones2, axis = 2)

array([[7.  , 3.25],
       [5.  , 7.  ],
       [7.  , 9.25]])

El primer 7 es la media entre todos los valores de la primera fila (8, 7, 8, 5), el 3.25 es la media entre los valores de la segunda (2, 5, 4, 2), y así sucesivamente.

In [5]:
# Alguna función interesante adicional, nos permite convertir la lista inicial a las dimensiones que queramos, 3 agrupaciones
# de filas, dos filas por agrupación y dos columnas. Importante es que las dimensiones que queremos, multiplicadas tienen
# que ser igual al tamaño de los elementos de la lista que queremos particionar.
#En este caso 3 elementos, de 2 dimensiones, de 3 columnas
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], (3,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

# Correlaciones entre variables

In [11]:
# Correlaciones entre dos variables.
# Una correlación es una relación lineal entre dos variables cuantitativas se representa como el cociente entre la covarianza
# de dos variables y el producto entre sus desviaciones estándar. Puede tomar valores entre -1 y 1, 
# cuanto más cerca de estos extremos se encuentre la relación estamos hablando de correlaciones fuertes,
# también tenemos dependiendo de esa distancia moderadas, débil y muy débil.
import pandas as pd
import numpy as np

df = pd.read_csv("data/base_datos_2008.csv", nrows = 1000000)

Valor de r	Fuerza de relación
-1,0 A -0,5 o 1,0 a 0,5	Fuerte
-0,5 A -0,3 o 0,3 a 0,5	Moderada
-0,3 A -0,1 o 0,1 a 0,3	Débil
-0,1 A 0,1	Ninguna o muy débil

Para más información, podéis consultar la página:
https://www.cienciadedatos.net/documentos/24_correlacion_y_regresion_lineal

In [12]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[nan, nan],
       [nan, nan]])

In [13]:
# No existe correlación porque existen valores perdidos, vamos a quitarlos utilizando Pandas, el coeficiente de correlación
# no admite valores faltantes. Tenemos que imputarlos o quitarlos, en este caso los quitamos.
df.dropna(inplace = True, subset = ["ArrDelay", "DepDelay"])

In [14]:
# Ahora vemos una matriz de correlación entre ambas variables. Estas dos variables están muy relacionadas (0.9349), 
# retraso del avión al salir y al llegar. 
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[1.        , 0.93490112],
       [0.93490112, 1.        ]])

In [15]:
# Añadimos una columna más y vemos que para este caso la correlación entre las dos primeras variables y la tercera es baja.
np.corrcoef([df["ArrDelay"], df["DepDelay"], df["DepTime"]])

array([[1.        , 0.93490112, 0.17978801],
       [0.93490112, 1.        , 0.21229661],
       [0.17978801, 0.21229661, 1.        ]])

In [16]:
df.drop(inplace = True, columns = ["Year", "Cancelled", "Diverted"])

In [17]:
# Hemos suprimido todas las columnas que no tienen valores numéricos. Ahora vemos la matriz de correlación.
df.corr()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,CRSElapsedTime,...,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Month,1.000000,-0.015050,0.030930,0.005771,0.001497,-0.007122,-0.009800,0.079810,-0.074488,-0.076087,...,0.031751,0.032285,-0.070562,-0.039301,-0.028302,-0.007918,0.023720,-0.018685,-0.000285,0.035021
DayofMonth,-0.015050,1.000000,-0.051893,-0.004149,-0.002338,0.001970,-0.000563,-0.005089,0.009748,0.005772,...,-0.016971,-0.025893,0.004336,-0.013975,0.020010,-0.026833,0.002860,0.046824,-0.018356,-0.010162
DayOfWeek,0.030930,-0.051893,1.000000,0.006505,0.010266,0.005845,0.007485,-0.003372,0.005525,0.012497,...,-0.020013,-0.009137,0.013937,0.007376,-0.023813,0.011215,-0.004178,-0.051235,0.008752,-0.002767
DepTime,0.005771,-0.004149,0.006505,1.000000,0.967093,0.718832,0.801405,-0.001497,-0.033971,-0.025449,...,0.179788,0.212297,-0.021899,-0.028305,-0.007641,0.013935,0.004591,-0.031814,-0.008924,0.219831
CRSDepTime,0.001497,-0.002338,0.010266,0.967093,1.000000,0.701446,0.800630,-0.013377,-0.031518,-0.020645,...,0.102853,0.132519,-0.014220,-0.032370,-0.018797,-0.046834,-0.022649,-0.074218,-0.009042,0.187314
ArrTime,-0.007122,0.001970,0.005845,0.718832,0.701446,1.000000,0.857240,-0.011925,0.027351,0.031429,...,0.073489,0.087577,0.026093,0.009363,0.010162,-0.044245,-0.018817,0.016260,-0.004983,0.014447
CRSArrTime,-0.009800,-0.000563,0.007485,0.801405,0.800630,0.857240,1.000000,-0.025392,0.036679,0.047353,...,0.098478,0.126896,0.044240,-0.002497,0.000617,-0.047146,-0.018615,-0.048304,-0.008037,0.161782
FlightNum,0.079810,-0.005089,-0.003372,-0.001497,-0.013377,-0.011925,-0.025392,1.000000,-0.289356,-0.302250,...,0.068460,0.053206,-0.333416,0.023670,0.073521,0.094233,0.066190,0.010670,-0.006524,-0.021083
ActualElapsedTime,-0.074488,0.009748,0.005525,-0.033971,-0.031518,0.027351,0.036679,-0.289356,1.000000,0.977603,...,0.062966,0.020822,0.956349,0.158391,0.256360,-0.044983,-0.010370,0.188094,-0.001425,-0.091541
CRSElapsedTime,-0.076087,0.005772,0.012497,-0.025449,-0.020645,0.031429,0.047353,-0.302250,0.977603,1.000000,...,-0.022951,0.009131,0.978077,0.099275,0.123392,-0.010326,-0.024111,0.046358,0.001212,-0.046930
AirTime,-0.069707,0.007797,0.009195,-0.031907,-0.027183,0.026009,0.038180,-0.314668,0.983909,0.987368,...,0.004612,0.004522,0.975308,0.082392,0.094641,-0.028101,-0.027663,0.075806,0.001673,-0.064661
ArrDelay,0.031751,-0.016971,-0.020013,0.179788,0.102853,0.073489,0.098478,0.068460,0.062966,-0.022951,...,1.000000,0.934901,-0.026296,0.118424,0.309567,0.476940,0.279551,0.357162,-0.006260,0.507945
DepDelay,0.032285,-0.025893,-0.009137,0.212297,0.132519,0.087577,0.126896,0.053206,0.020822,0.009131,...,0.934901,1.000000,0.004399,0.020033,0.092959,0.506839,0.255680,0.167083,-0.002860,0.551564
Distance,-0.070562,0.004336,0.013937,-0.021899,-0.014220,0.026093,0.044240,-0.333416,0.956349,0.978077,...,-0.026296,0.004399,1.000000,0.070510,0.076459,-0.009092,-0.028149,0.018185,0.002166,-0.035306
TaxiIn,-0.039301,-0.013975,0.007376,-0.028305,-0.032370,0.009363,-0.002497,0.023670,0.158391,0.099275,...,0.118424,0.020033,0.070510,1.000000,0.048334,-0.042360,0.006748,0.199826,-0.007527,-0.046949
TaxiOut,-0.028302,0.020010,-0.023813,-0.007641,-0.018797,0.010162,0.000617,0.073521,0.256360,0.123392,...,0.309567,0.092959,0.076459,0.048334,1.000000,-0.060460,0.064435,0.410929,-0.009747,-0.108578
CarrierDelay,-0.007918,-0.026833,0.011215,0.013935,-0.046834,-0.044245,-0.047146,0.094233,-0.044983,-0.010326,...,0.476940,0.506839,-0.009092,-0.042360,-0.060460,1.000000,-0.059067,-0.139575,-0.019080,-0.155135
WeatherDelay,0.023720,0.002860,-0.004178,0.004591,-0.022649,-0.018817,-0.018615,0.066190,-0.010370,-0.024111,...,0.279551,0.255680,-0.028149,0.006748,0.064435,-0.059067,1.000000,-0.018083,-0.007717,-0.049814
NASDelay,-0.018685,0.046824,-0.051235,-0.031814,-0.074218,0.016260,-0.048304,0.010670,0.188094,0.046358,...,0.357162,0.167083,0.018185,0.199826,0.410929,-0.139575,-0.018083,1.000000,-0.017256,-0.150310
SecurityDelay,-0.000285,-0.018356,0.008752,-0.008924,-0.009042,-0.004983,-0.008037,-0.006524,-0.001425,0.001212,...,-0.006260,-0.002860,0.002166,-0.007527,-0.009747,-0.019080,-0.007717,-0.017256,1.000000,-0.016765
LateAircraftDelay,0.035021,-0.010162,-0.002767,0.219831,0.187314,0.014447,0.161782,-0.021083,-0.091541,-0.046930,...,0.507945,0.551564,-0.035306,-0.046949,-0.108578,-0.155135,-0.049814,-0.150310,-0.016765,1.000000

In [18]:
# Podemos estudiar una a una las correlaciones entre filas y columnas. 
# Para visualizar gráficamente la matriz, redondeando a tres decimales (round) y aplicamos estilo bakcground que mostrará
# un degradado según la intensidad de la correlación.
# Esto nos permite hacer una inspección de nuestra BD, analizando correlaciones que en principio no habíamos considerado.

# df.drop(inplace = True, columns = ["Month"])
corr = round (df.corr(), 3)
corr.style.background_gradient()

# Todo esto nos permite hacer un análisis inicial de corelaciones entre variables de nuestra base de datos.

# Test de Chi-Cuadrado

In [19]:
# El test chi-cuadrado permite comparar y hacer un estudio entre el valor observado y esperado en un conjunto de datos 
# y comprobar si existe dependencia entre variables.

import pandas as pd
import numpy as np

df = pd.read_csv("data/base_datos_2008.csv")

# Sumas diferencias al cuadrado entre nuestros valores observados y los esperados...

$$X^2 = \sum{(observado_{i} - esperado_{i})^2}\div(esperado_{i})$$

https://es.wikihow.com/calcular-el-p-valor

In [20]:
# Al fijar una semilla, cuando quiera replicar el código obtendremos los mismos resultados.
np.random.seed(0)

# Seleccionamos los vuelos con origen en las tres ubicaciones seleccionadas.
df = df[df["Origin"].isin(["HOU", "ATL", "IND"])]

# Una vez aplicado el filtro, reordenamos la BD y seleccionamos las primeras 10.000 filas para realizar un test
df = df.sample(frac = 1)
df = df[0:10000]

In [21]:
# Creamos una nueva variable BigDelay que tendrá el valor True cuando el retraso de llegada sea > 30 minutos, falso en caso 
# contrario.
df["BigDelay"] = df["ArrDelay"] > 30
observados = pd.crosstab(index = df["BigDelay"], columns = df["Origin"], margins = True) 

# margins = True nos da los totales a la derecha y abajo.

In [22]:
# Hemos generado una tabla de contingencia.
# 6927 son los vuelos de Atlanta que se han retrasado menos de 30 minutos.
observados

Origin     ATL   HOU  IND    All
BigDelay
False     6927   883  765   8575
True      1197   129   99   1425
All       8124  1012  864  10000

In [23]:
# A continuación importamos el paquete que va a realizar el test
from scipy.stats import chi2_contingency

In [24]:
test = chi2_contingency(observados)

In [25]:
# El primer dato que nos devuelve es el estadístico (suma de las diferencias al cuadrado)
# El segundo es el p-valor, el p-valor 
# Finalmente la tabla de valores esperados.

test

(8.939538453043031,
 0.17700704816414425,
 6,
 array([[ 6966.33,   867.79,   740.88,  8575.  ],
        [ 1157.67,   144.21,   123.12,  1425.  ],
        [ 8124.  ,  1012.  ,   864.  , 10000.  ]]))

In [26]:
# Convertimos la tabla de los valores esperados en un Dataframe y la visualizamos
esperados = pd.DataFrame (test[3])

In [27]:
esperados

         0        1       2        3
0  6966.33   867.79  740.88   8575.0
1  1157.67   144.21  123.12   1425.0
2  8124.00  1012.00  864.00  10000.0

In [28]:
esperados_rel = round(esperados.apply(lambda r: r/len(df) * 100, axis = 1), 2)
observados_rel = round(observados.apply(lambda r: r/len(df) * 100, axis = 1), 2)

In [29]:
observados_rel

Origin      ATL    HOU   IND     All
BigDelay
False     69.27   8.83  7.65   85.75
True      11.97   1.29  0.99   14.25
All       81.24  10.12  8.64  100.00

In [30]:
esperados_rel

       0      1     2       3
0  69.66   8.68  7.41   85.75
1  11.58   1.44  1.23   14.25
2  81.24  10.12  8.64  100.00

In [31]:
# Test chi-cuadrado nos permite comparar los elementos esperados vs observados, para poder generar un estadístico
# Si el p-valor < 0,05 hay diferencias significativas. Hay relación entre variables.
# Si el p-valor > 0,05 no hay diferencias significativas. No hay relación entre variables.

test[1]

0.17700704816414425

In [ ]:
# No podemos afirmar en este caso que haya relación entre variables.

# Análisis de datos externos

In [99]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/Cap 8/base_datos_2008.csv", nrows = 100000)
# Miraremos cómo detectar aquellos datos que toman valores extremadamente grandes o pequeños (outlier)

In [100]:
# Extraemos la columna ArrDelay y eliminamos los datos faltantes de esta columna
x = df["ArrDelay"].dropna()

In [101]:
# Seleccionamos los cuartiles
Q1 = np.percentile(x, 25)
Q3 = np.percentile(x, 75)
# Calculamos el rango intercuartílico, diferencia entre el tercer cuartil y el primer cuartil
# La mediana es el Q2.
rangointer = Q3 - Q1

In [102]:
umbralsuperior = Q3 + 1.5 * rangointer
umbralinferior = Q1 - 1.5 * rangointer

In [103]:
umbralsuperior

38.5

In [104]:
umbralinferior

-37.5

In [105]:
# Los casos que están por encima del umbralsuperior, están alrededor de... 8% por encima.
np.mean(x > umbralsuperior)

0.08387201361729721

In [106]:
# En este segundo caso, los casos por debajo del umbral inferior están alrededor de... 0,2% por debajo.
np.mean(x < umbralinferior)

0.0019048005025431114

In [107]:
# Por tanto, las medidas no están simétricas. Vamos a ver cómo podemos estudiar varias variables a la vez.
from sklearn.covariance import EllipticEnvelope

In [108]:
# Establecemos un modelo que nos va a seleccionar el 1% de los datos que están más alejados de nuestros datos más centrados.
outliers = EllipticEnvelope(contamination = .01)

In [110]:
# Definimos una lista de nuestra BD, todas cuantitativas y asumimos que su distribución es Gaussiana.
var_list = ["DepDelay", "TaxiIn", "TaxiOut", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]

In [111]:
# Definimos de nuevo la variable x con los valores que nos interesan (lista)
x = np.array(df.loc[:, var_list].dropna())

In [112]:
# Pasamos a entrenar nuestro modelo.
outliers.fit(x)

EllipticEnvelope(assume_centered=False, contamination=0.01, random_state=None,
                 store_precision=True, support_fraction=None)

In [113]:
# Predicción de los valores que forman parte del 1% que queremos detectar.
pred = outliers.predict(x)

In [114]:
pred

array([1, 1, 1, ..., 1, 1, 1])

In [119]:
# Nos interesa detectar los -1
elips_outliers = np.where(pred == -1)[0]

In [120]:
# Lista de todos los index de aquellos casos que están muy alejados de los valores centrales de las variables estudiadas.
# Sirven para observar en nuestra BD aquellos valores que sean extremos y que requieran de nuestra atención.
elips_outliers

array([   18,    53,    56,   273,   276,   285,   298,   308,   626,
         627,   628,  1330,  1412,  1503,  1744,  1827,  1842,  1863,
        1887,  1911,  1914,  2050,  2103,  2129,  2256,  2313,  2505,
        2613,  2697,  2711,  2715,  2719,  2725,  2728,  2803,  3413,
        3437,  3615,  3688,  3733,  3814,  3828,  3835,  3941,  3981,
        3997,  4047,  4048,  4215,  4265,  4306,  4430,  4437,  4512,
        4924,  5841,  5972,  5974,  5975,  5982,  5983,  5984,  5985,
        5986,  5988,  5994,  5996,  5999,  6024,  6699,  6700,  6919,
        6921,  6923,  6924,  6928,  6929,  6931,  6935,  7311,  7480,
        7698,  7701,  7702,  7707,  7715,  8267,  8566,  8730,  8900,
        9080,  9105,  9107,  9526,  9539,  9694,  9739,  9743,  9746,
        9876,  9883,  9958, 10106, 10159, 10185, 10216, 10250, 10341,
       10426, 10554, 10736, 10747, 10910, 11237, 11242, 11572, 11577,
       12502, 13004, 13005, 13007, 13276, 13278, 13334, 13338, 13714,
       13787, 13994, 14088, 14257, 14282, 14358, 14492, 14493, 14558,
       14588, 14621, 14644, 14647, 14775, 14789, 14792, 14801, 14858,
       14881, 14907, 14940, 14947, 14948, 15005, 15009, 15136, 15150,
       15195, 15202, 15287, 15381, 15566, 15596, 15827, 15962, 16063,
       16532, 16740, 17080, 17099, 17177, 17230, 17261, 17559, 17592,
       17596, 17659, 17671, 17682, 17771, 17776, 17879, 17995, 18129,
       18225, 18229, 18496, 18594, 18784, 18803, 18819, 18829, 18956,
       19079, 19128, 19161, 19173, 19224, 19225, 19232, 19235],
      dtype=int64)

In [ ]:
import pandas as pd
import numpy as np

# Utilizamos la biblioteca joblib para ejecutar procesos en paralelo.
from joblib import Parallel, delayed

df = pd.read_csv("../../data/Cap 8/base_datos_2008.csv", nrows = 100000)

In [ ]:
df_sub = df[["CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]]
df_sub.head(10)

In [ ]:
def retraso_maximo (fila): 
    if not np.isnan(fila).any():
        names = ["CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]
        return names[fila.index(max(fila))]
    else:
        return "None"

In [ ]:
results = []
for fila in df_sub.values.tolist():
    results.append(retraso_maximo(fila))

In [ ]:
results

In [ ]:
# Implementamos la función anterior, paralelizando el proceso.
result = Parallel(n_jobs = 2, backend = "multiprocessing") (map(delayed(retraso_maximo), df_sub.values.tolist()))

In [ ]:
result

# Transformar un dataframe en una BD relacional

In [121]:
import pandas as pd
data = [(1, "Pedro", "Rondo", 30, 1, "Libreta", 1.2,.4,0.8,3, "03-02-2020"),
       (1, "Pedro", "Rondo", 30, 2, "Bolígrafo", 0.4,0.15,0.25,1, "03-02-2020"),
       (1, "Pedro", "Rondo", 30, 1, "Libreta", 1.2,.4,0.8,2, "15-02-2020"),
       (2, "Juan", "López", 22, 2, "Bolígrafo", 0.4,0.15,0.25,4, "01-02-2020"),
       (2, "Juan", "López", 22, 1, "Libreta", 1.2,.4,0.8,10, "05-03-2020"),
       (3, "María", "García", 25, 1, "Libreta", 1.2,.4,0.8,20, "13-04-2020"),
       (3, "María", "García", 25, 2, "Bolígrafo", 0.4,0.15,0.25,1, "09-02-2020"),
       (3, "María", "García", 25, 2, "Libreta",  0.4,0.15,0.25,3, "03-04-2020")]
labels = ["Comprador_id", "Nombre", "Apellido", "Edad", "Producto_id", "Producto", "Precio", "Coste", "Margen", 
          "Cantidad", "Fecha"]

In [122]:
df = pd.DataFrame.from_records(data, columns = labels)

In [123]:
# Mostramos los datos
df

,Comprador_id,Nombre,Apellido,Edad,Producto_id,Producto,Precio,Coste,Margen,Cantidad,Fecha
0,1,Pedro,Rondo,30,1,Libreta,1.2,0.40,0.80,3,03-02-2020
1,1,Pedro,Rondo,30,2,Bolígrafo,0.4,0.15,0.25,1,03-02-2020
2,1,Pedro,Rondo,30,1,Libreta,1.2,0.40,0.80,2,15-02-2020
3,2,Juan,López,22,2,Bolígrafo,0.4,0.15,0.25,4,01-02-2020
4,2,Juan,López,22,1,Libreta,1.2,0.40,0.80,10,05-03-2020
5,3,María,García,25,1,Libreta,1.2,0.40,0.80,20,13-04-2020
6,3,María,García,25,2,Bolígrafo,0.4,0.15,0.25,1,09-02-2020
7,3,María,García,25,2,Libreta,0.4,0.15,0.25,3,03-04-2020

In [124]:
# Se puede ver que hay mucha información repetida, grabamos múltiples veces campos.
# Partimos esta tabla en tres tablas con la información necesaria por tabla.
compradores = df.drop_duplicates(subset = "Comprador_id", keep = "first")

In [125]:
compradores

,Comprador_id,Nombre,Apellido,Edad,Producto_id,Producto,Precio,Coste,Margen,Cantidad,Fecha
0,1,Pedro,Rondo,30,1,Libreta,1.2,0.40,0.80,3,03-02-2020
3,2,Juan,López,22,2,Bolígrafo,0.4,0.15,0.25,4,01-02-2020
5,3,María,García,25,1,Libreta,1.2,0.40,0.80,20,13-04-2020

Como se puede ver solo necesitamos la información relativa a tres compradores. Seguimos guardando demasiada información
para la tabla de clientes, habrá que eliminar los campos no necesarios.

In [126]:
# Eliminamos todas las columnas que no necesitemos de la tabla de compradores.
compradores = compradores [["Comprador_id", "Nombre", "Apellido", "Edad"]]
compradores

   Comprador_id Nombre Apellido  Edad
0             1  Pedro    Rondo    30
3             2   Juan    López    22
5             3  María   García    25

Estamos normalizando los datos de la tabla de compradores (clientes) con los datos imprescindibles y diferenciales.
Replicamos el proceso para crear la tabla de productos y la de compras.

In [127]:
# Creamos una tabla de productos.
productos = df.drop_duplicates(subset = "Producto_id", keep = "first")

In [128]:
productos

,Comprador_id,Nombre,Apellido,Edad,Producto_id,Producto,Precio,Coste,Margen,Cantidad,Fecha
0,1,Pedro,Rondo,30,1,Libreta,1.2,0.40,0.80,3,03-02-2020
1,1,Pedro,Rondo,30,2,Bolígrafo,0.4,0.15,0.25,1,03-02-2020

In [129]:
# Ahora nos quedamos con las columnas relativas a los productos.
productos = productos [["Producto_id", "Producto", "Precio", "Coste", "Margen"]]

In [130]:
productos

   Producto_id   Producto  Precio  Coste  Margen
0            1    Libreta     1.2   0.40    0.80
1            2  Bolígrafo     0.4   0.15    0.25

La información generada es la necesaria para definir los datos de productos. Por último, generamos la tabla de compra.

In [131]:
compras = df[["Comprador_id", "Producto_id", "Fecha", "Cantidad"]]
compras

   Comprador_id  Producto_id       Fecha  Cantidad
0             1            1  03-02-2020         3
1             1            2  03-02-2020         1
2             1            1  15-02-2020         2
3             2            2  01-02-2020         4
4             2            1  05-03-2020        10
5             3            1  13-04-2020        20
6             3            2  09-02-2020         1
7             3            2  03-04-2020         3

Tenemos la tabla de compras que unirá la tabla de compradores con la de productos.

# Paralelizar bucles

In [1]:
import pandas as pd
import numpy as np
from joblib import Parallel, delayed

df = pd.read_csv("../../data/Cap 8/base_datos_2008.csv", nrows = 100000)

In [2]:
df_sub = df[["CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]]
df_sub.head(10)

   CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay
0           NaN           NaN       NaN            NaN                NaN
1           NaN           NaN       NaN            NaN                NaN
2           NaN           NaN       NaN            NaN                NaN
3           NaN           NaN       NaN            NaN                NaN
4           2.0           0.0       0.0            0.0               32.0
5           NaN           NaN       NaN            NaN                NaN
6          10.0           0.0       0.0            0.0               47.0
7           NaN           NaN       NaN            NaN                NaN
8           NaN           NaN       NaN            NaN                NaN
9           NaN           NaN       NaN            NaN                NaN

In [3]:
# Vamos a trabajar con la estructura creada anteriormente.
# Vamos a buscar el retraso máximo dentro de las filas y campos anteriores.
def retraso_maximo(fila):
    if not np.isnan(fila).any():
        names = ["CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]
        return names[fila.index(max(fila))]
    else:
        return "None"

In [4]:
results = []
for fila in df_sub.values.tolist():
    results.append(retraso_maximo(fila))

In [5]:
results

['None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'SecurityDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'NASDelay',
 'CarrierDelay',
 'NASDelay',
 'None',
 'NASDelay',
 'NASDelay',
 'LateAircraftDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'SecurityDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'NASDelay',
 'SecurityDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'SecurityDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'WeatherDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'WeatherDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'NASDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'NASDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'WeatherDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'NASDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 ...]

In [6]:
# Vamos a implementar esto pero paralelizando el proceso.
result = Parallel(n_jobs = 1, backend = "multiprocessing") (
    map (delayed(retraso_maximo), df_sub.values.tolist()))

In [7]:
result

['None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'SecurityDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'NASDelay',
 'CarrierDelay',
 'NASDelay',
 'None',
 'NASDelay',
 'NASDelay',
 'LateAircraftDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'SecurityDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'NASDelay',
 'SecurityDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'SecurityDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'NASDelay',
 'LateAircraftDelay',
 'NASDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'NASDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'WeatherDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'NASDelay',
 'None',
 'None',
 'WeatherDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'NASDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'NASDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'NASDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'WeatherDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'None',
 'CarrierDelay',
 'NASDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'CarrierDelay',
 'CarrierDelay',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'LateAircraftDelay',
 'None',
 'None',
 'LateAircraftDelay',
 'None',
 'LateAircraftDelay',
 'None',
 'CarrierDelay',
 'LateAircraftDelay',
 'CarrierDelay',
 'None',
 'None',
 'None',
 ...]